name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
    
jobs:
  test-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.16.3', '1.15']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{matrix.go}}
      - run: go env -w GO111MODULE=auto
      - run: go test
      - run: go run math.go

  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.3'
      - run: go env -w GO111MODULE=auto
      - run: go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with: 
          push: false
          tags: vitordeoliveira/fc2-ci-go:latest
